#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE auth_db;
    CREATE DATABASE vehicle_db;
    CREATE DATABASE auction_db;
    CREATE DATABASE bid_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE notification_db;
    
    GRANT ALL PRIVILEGES ON DATABASE auth_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE vehicle_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE auction_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE bid_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE payment_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO $POSTGRES_USER;
EOSQL

echo "All databases created successfully!"